### PR TITLE
Branch fix ped

### LINKED ISSUE #89: [PE-D][Tester B] Programme crashes when i key in expense description with punctuation
When i enter "addExpense eat, tmr /amt 99", and proceed to viewExpenses, the programme crashes with a NumberFormatException. Maybe this could be caught by the application before it crashes the programme

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SebasFok/ped#1

### LINKED ISSUE #97: [PE-D][Tester C] Adding large income/expense amounts results in unexpected amount.
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Adding large values for the amount field results in an unexpected amount being added (a small decimal number). 

Steps to reproduce:
1. Enter 'addIncome test /amt 999999999'
2. Enter 'viewIncomes'
3. Observe the Amount value

Expected behaviour:
The amount value should not change, OR show an error message to the user stating that large amounts are not accepted.

Actual behaviour:
The amount value is changed. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lckjosh/ped#5

### LINKED ISSUE #102: [PE-D][Tester B] Long string in addExpense
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>

Adding a long string messes with the formatting or the table

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: SebasFok/ped#4

### PR DESCRIPTION
**Pull request by BenedictChannn**

### CODE REVIEW

File: src/main/java/cashleh/parser/Parser.java [hunk 1]
```diff
@@ -171,6 +177,11 @@ private Income getIncome(String input) throws CashLehParsingException {
         double incomeAmt;
         try {
             incomeAmt = Double.parseDouble(incomeAmtString);
+            if (incomeAmt > MAX_AMT) {
+                throw new CashLehParsingException("Amount entered is too large! " +
+                    "Please split up your transaction into smaller ones " +
```
Comment (danielpappa) [inline src/main/java/cashleh/parser/Parser.java:182]: Nice way of handling too large numbers! Maybe consider setting the MAX_AMT to 9999999.99 as it is a double

**Review by danielpappa — APPROVED** [review]
LGTM

**Review by mcmc101001 — APPROVED** [review]
