### PR TITLE
Fixed various bugs in reported issues

### LINKED ISSUE #83: [PE-D][Tester E] Description and Amt bug in addIncome
Input given: 

addIncome !@##$@$ testing testing /amt  -999

User Guide states:

1. Description cannot contain punctuation of special characters. However I was able to input them. 

2. Amount must be positive number but entering -999 works, and it shows as -999 on the UI.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yingx9/ped#4

### LINKED ISSUE #92: [PE-D][Tester A] Program accepts negative values for amounts
Program does not throw error message when user inputs negative values for amount

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: NeoMinWei/ped#8

### LINKED ISSUE #93: [PE-D][Tester E] Description and Amount bug in addExpense
**Steps to reproduce:**

Enter:

addExpense !@##$@$ testing testing /amt -999

**Expected**

Error message not allowing input of punctuation, special characters in description and negative number for amount

**Actual**

User Guide states:

Description cannot contain punctuation of special characters. However I was able to input them.

Amount must be positive number but entering -999 works, and it shows as -999 on the UI.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yingx9/ped#8

### LINKED ISSUE #94: [PE-D][Tester C] No input validation for negative expense/income amount
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Upon entering a negative amount for either income or expense, the program takes it as a negative number. 

Steps to reproduce: (for income, applies to expense as well)
1. Enter 'addIncome test /amt -100'
2. Enter 'viewIncomes'
3. Observe that there is a negative income. 

Expected behaviour:
An error message preventing the user from entering negative income/expense

Actual behaviour:
Negative income/expense is accepted. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: lckjosh/ped#4

### LINKED ISSUE #98: [PE-D][Tester A] Error message is not specific when inputting impossible date
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Error message says to follow correct format, but the error is in impossible date

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: NeoMinWei/ped#9

### PR DESCRIPTION
**Pull request by mcmc101001**

### CODE REVIEW

**Review by BenedictChannn — APPROVED** [review]
LGTM

File: src/main/java/cashleh/parser/Parser.java [hunk 1]
```diff
@@ -127,6 +127,9 @@ private Expense getExpense(String input) throws CashLehParsingException {
         double expenseAmt;
         try {
             expenseAmt = Double.parseDouble(expenseAmtString);
+            if (expenseAmt < 0) {
+                throw new CashLehParsingException("Please enter a positive expense amount!");
```
Comment (BenedictChannn) [inline src/main/java/cashleh/parser/Parser.java]: Maybe can rephrase to "Please enter the absolute amount" because positive expense may sound a bit confusing?

File: src/main/java/cashleh/CashLeh.java [hunk 2]
```diff
@@ -30,8 +30,7 @@ public void run() {
                     + " / /___/ /_/ (__  ) / / / /___/  __/ / / /_/\n"
                     + " \\____/\\__,_/____/_/ /_/_____/\\___/_/ /_(_)\n";
         String userGuideLink = ("Here is the link to the user guide:"
-                + "https://docs.google.com/document/d/"
-                + "15h45BB5kMkTZ6bkwUHujpYwxVVl80tNEyNUsEVyk5AQ/edit?usp=drive_link");
+                + "https://ay2324s1-cs2113-w12-2.github.io/tp/UserGuide.html");
```
Comment (danielpappa) [inline src/main/java/cashleh/CashLeh.java]: Maybe we could insert a line break before displaying the link, in order to increase its visibility and make it easier to copy.

File: src/main/java/cashleh/parser/Parser.java [hunk 3]
```diff
@@ -171,6 +174,9 @@ private Income getIncome(String input) throws CashLehParsingException {
         double incomeAmt;
         try {
             incomeAmt = Double.parseDouble(incomeAmtString);
+            if (incomeAmt < 0) {
+                throw new CashLehParsingException("Please enter a positive expense amount!");
```
Comment (danielpappa) [inline src/main/java/cashleh/parser/Parser.java]: Shouldn't this say "Please enter a positive income amount?"?

**Review by danielpappa — CHANGES_REQUESTED** [review]
LGTM

**Review by danielpappa — APPROVED** [review]
