### PR TITLE
Fix logging issue

### LINKED ISSUE #79: [PE-D][Tester A] Logging messages shown to user
Logging messages shown after each command

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: NeoMinWei/ped#3

### PR DESCRIPTION
**Pull request by mcmc101001**

### CODE REVIEW

File: src/main/java/cashleh/commands/Command.java [hunk 1]
```diff
@@ -12,17 +12,8 @@ public class Command {
...
-    public Command(int index) {
-        this.index = index;
-    }
-
     public Command() {
-    }
-
-    public int getIndex() {
-        return this.index;
+        this.logger.setLevel(loggerLevel);
```
Comment (danielpappa) [inline src/main/java/cashleh/commands/Command.java:16]: Nice way of disabling logging. Maybe in the next version we can also create a .txt file containing all the logging information separately.

**Review by danielpappa — APPROVED** [review]
LGTM
